### ISSUE TITLE
No module named torch2trt.converters.Identity

### ISSUE THREAD

**Issue by huangrichen11** [NVIDIA-AI-IOT/torch2trt#117]
after install torch2trt, No module named torch2trt.converters.Identity was encountered when import torch2trt

**Comment by czs1886** [comment]
Same here, have you solved it?

**Comment by czs1886** [comment]
I solved it by manually cp identity.py, relu.py relu6.py into the converters directory.

**Comment by lrh454830526** [comment]
Have you  solved the probleam?I have met the issue too and I have no idea how to deal with it

**Comment by ysyyork** [comment]
This is probably you clone this repo into a filesystem like exfat who can't differentiate uppercase and lowercase letters in filename. In the convertor folder there are `Identity.py` vs `identity.py`. the clone will silently merge see two files as one and use the lowercase filename. I think this should be changed otherwise compatibility will be bad for this repo
