### ISSUE TITLE
Increase of memory usage for TensorRT models

### ISSUE THREAD

**Issue by amirassov** [NVIDIA-AI-IOT/torch2trt#237]
I found that the tensorrt model (with fp16 or int8) uses more memory than pytorch model. Is it normal?

### Pytorch model: 
```
import torch
from torch2trt import torch2trt
from torchvision.models.alexnet import alexnet

model = alexnet(pretrained=True).eval().cuda()
```
_Memory usage: 838 MB_

### Convert:
```
import torch
from torch2trt import torch2trt
from torchvision.models.alexnet import alexnet

model = alexnet(pretrained=True).eval().cuda()
x = torch.ones((1, 3, 224, 224)).cuda()
model_trt = torch2trt(model, [x], fp16_mode=True)
torch.save(model_trt.state_dict(), 'alexnet_trt.pth')
```

### Tensorrt model:
```
import torch
from torch2trt import TRTModule

model_trt = TRTModule()
model_trt.load_state_dict(torch.load('alexnet_trt.pth'))
```
_Memory usage: 1088 MB_

1. PyTorch: 1.3.0
2. TensorRT: 6.0.1.5
3. Torchvision: 0.5.0
4. Platform: Ubuntu 18.04, CUDA 10.2, Python 3.6.9

**Comment by jaybdub** [comment]
Hi amirassov,

Thanks for reaching out!  This may be expected behavior, especially since the TRTModule initializes the runtime context before execution, which I believe includes the memory allocated for activation buffers.  

Do you experience the same memory delta even after executing the PyTorch module on data?  

Best,
John

**Comment by benjaminhon** [comment]
@jaybdub can i check in the event that there is not enough memory that tensorrt will release some models which are not used to load the current used model?
