### ISSUE TITLE
Segmentation fault (core dumped) randomly after load the int8 calibration table file? 

### ISSUE THREAD

**Issue by yuzhiyiliu** [NVIDIA-AI-IOT/torch2trt#267]
Hi，
    These are the two functions I completed in the calibration.py.
    They seem to be fine, but I get a Segmentation fault (core dumped) randomly after load the int8 calibration table file. There seems to be a problem using the return value of read_calibration_cache, unfortunately i can‘t step through the bug. Looking forward to your feedback.

    def read_calibration_cache(self, *args, **kwargs):
        # If there is a cache, use it instead of calibrating again. Otherwise, implicitly return None.
        if os.path.exists(self.cache_file):
            with open(self.cache_file, "rb") as f:
                cache = f.read()
                f.close()
                return cache
        else:
            return None

    def write_calibration_cache(self, cache, *args, **kwargs):
        with open(self.cache_file, "wb") as f:
            f.write(cache)
            f.close()

**Comment by yuzhiyiliu** [comment]
A new problem!
**Create the int8 model for the second time, the saved int8 calibration table file will be modified.**
In order to make the problem obvious, I set read-only permissions on the saved int8 calibration table file.
When I generate the int8 model, I get `[Errno 13] Permission denied: 'int8_calib_table.bin'`

saved:
(Unnamed Layer* 324) [Convolution]_output: 3706ff72
(Unnamed Layer* 325) [Scale]_output: 37f803b7
(Unnamed Layer* 326) [Activation]_output: 3b812b82
(Unnamed Layer* 327) [ElementWise]_output: 3746a826
(Unnamed Layer* 328) [Pooling]_output: 3746a826

modified:
(Unnamed Layer* 324) [Convolution]_output: 3706ff72
(Unnamed Layer* 325) [Scale]_output: 3
(Unnamed Layer* 327) [ElementWise]_output: 3746a826
(Unnamed Layer* 328) [Pooling]_output: 3746a826

**Comment by zhujiandream** [comment]
Dear my friend,   I had the same problem too.

I think it caused by we know too much about the TensorRT INT8 calibration coding.

"read_calibration_cache" &  "write_calibration_cache"  function should not be changed, and the .cache file is not required.

Just use calibration dataset to do the INT8 calibration, and

save:
torch.save(model_trt.state_dict(), 'alexnet_trt.pth')

load:
from torch2trt import TRTModule
model_trt2 = TRTModule()
model_trt2.load_state_dict(torch.load('alexnet_trt.pth'))

"y_trt = model_tr2(x)"       would do the inference in TensorRT INT 8 mode

**Comment by yuzhiyiliu** [comment]
Wow~~ Great idea! This method is just like fp32 and fp16, which is very convenient to use. 感谢大王

**Comment by GregHWayne** [comment]
how do you resolve your problem, "Just use calibration dataset to do the INT8 calibration" ?
"Misc Error in createRegionScalesFromTensorScales" seems quite suspicious，doubt relative to op split ?

**Comment by yuanzhedong** [comment]
@GregHWayne for my case I got the error because I'm trying to use the same script to convert another model, but the prev model's calibration cache is not cleaned，as @zhujiandream mentioned, it works after I remove the cache file. More info can be found here: https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Int8/Calibrator.html#tensorrt.IInt8Calibrator.read_calibration_cache
