### ISSUE TITLE
ClipParameters Assertion Error when converting HarDNet68 to INT8

### ISSUE THREAD

**Issue by rrivera1849** [NVIDIA-AI-IOT/torch2trt#401]
Hello Everyone,

I'm trying evaluate [HarDNet68](https://github.com/PingoLH/Pytorch-HarDNet) using TensorRT with INT8 quantization on the NVIDIA Jetson AGX Xavier. This is the code that I'm using to do so:
```python
import torch

from torch2trt import torch2trt

device = torch.device('cuda')

model = torch.hub.load("PingoLH/PyTorch-HarDNet", "hardnet68").to(device)
x = torch.randn(1, 3, 550, 550).to(device)
trt_model = torch2trt(model, [x], int8_mode=True)
```

Which produces the following error:
```python
python3: helpers.cpp:534: nvinfer1::ClipParameters nvinfer1::scaleInt8ClipParametersByTensor(nvinfer1::ClipParameters, const nvinfer1::rt::EngineTensor&): Assertion `std::all_of(std::begin(hostScales) + getC(t.start), std::begin(hostScales) + getC(t.start) + getC(t.extent), [scale](float x) { return x == scale; })' failed.
```

What's interesting is that if I use FP16 quantization no error is produced. Any ideas as to how I might go about solving this issue? 

* PyTorch version - 1.4
* TensorRT version - 6.0.1.10
* Platform - NVIDIA Jetson AGX Xavier

**Comment by jaybdub** [comment]
Hi rrivera1849,

Thanks for reaching out!

Good to hear the network is working with FP16.

Unfortunately, I don't have an immediate answer regarding the int8 error so I would have to investigate.  In the meantime, here are some ideas to try

* Try increasing the batch size of your calibration dataset.  Currently it looks like you are using just 1 image.  Maybe try``x = torch.randn(64, 3, 550, 550).to(device)`` to start.
* Separately, you could try setting ``strict_type_constraints=True``.  But this may have other effects.

I'd try these separately, I'm not honestly sure what the issue is at the moment.  If I make progress on this I'll let you know.

Please let me know if this helps or you run into issues.

Best,
John

**Comment by rrivera1849** [comment]
Thanks for your quick response! Unfortunately I'm still getting the same error. Here's my code:

```python
import torch

from torch2trt import torch2trt

device = torch.device('cuda')

model = torch.hub.load("PingoLH/PyTorch-HarDNet", "hardnet68").to(device)
x = torch.randn(64, 3, 550, 550).to(device)
calibration_dset = torch.randn(64, 3, 550, 550).to(device)

trt_model = torch2trt(model, [x], int8_mode=True, int8_calib_dataset=calibration_dset, strict_type_constraints=True)
```

I've switched ```strict_type_constraints``` to False but it's still throwing the same error.

**Comment by rrivera1849** [comment]
Recently I pulled from master and this error seems to have gone away. Here's my commit hash: b0cc8e77a0fbd61e96b971a66bbc11326f77c6b5.
