### ISSUE TITLE
how to convert Deformation Convolution Layer into tensorRT layer

### ISSUE THREAD

**Issue by Johnson-yue** [NVIDIA-AI-IOT/torch2trt#479]

**Comment by jaybdub** [comment]
Hi @Johnson-yue ,

Thanks for reaching out!

This would likely require creating a TensorRT plugin with C++.  For example, here we have a plugin which calls the torch C++ API

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/plugins/interpolate.cpp#L207

Which then needs to have a converter like this

https://github.com/NVIDIA-AI-IOT/torch2trt/blob/master/torch2trt/converters/interpolate.py

You could potentially do something similiar, but latch into the C++/Cuda definition of deformable convolution

https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/blob/master/src/deform_conv_cuda_kernel.cu

This has some slight overhead, since the deformable convolution kernel in torchvision doesn't have an inplace method.  But may accomplish something satisfactory.

Please let me know if this helps or you have any questions.  Also, if you test this / works for your use case, I'd love to hear.

Best,
John

**Comment by Johnson-yue** [comment]
thank you ， I will try it later and if some work done， I will tell you
