### ISSUE TITLE
Encountered known unsupported method torch.matmul after adding custom matmul converter

### ISSUE THREAD

**Issue by kamilrzechowski** [NVIDIA-AI-IOT/torch2trt#587]
torch2trt does not contain matmul converter, so I added it myself. I created a file /torch2trt/torch2trt/converters/matmul.py and inserted the following code:

`from torch2trt.torch2trt import *
from torch2trt.module_test import add_module_test

@tensorrt_converter('torch.matmul')
def convert_matmul(ctx):
    print("Matmul called")
    input_a = ctx.method_args[0]
    input_b = ctx.method_args[1]
    input_a_trt, input_b_trt = trt_(ctx.network, input_a, input_b)
    output = ctx.method_return
    layer = ctx.network.add_matrix_multiply(input_a_trt, trt.MatrixOperation.NONE, input_b_trt, trt.MatrixOperation.NONE)
    output._trt = layer.get_output(0)`

After compiling the torch2trt again I still get the error:

Warning: Encountered known unsupported method torch.matmul
Warning: Encountered known unsupported method torch.matmul
Traceback (most recent call last):
  File "/workspace/scripts/test_trt.py", line 56, in <module>
    mask_model_trt = torch2trt(mask_model, [b4, zf_ori, template_mask], log_level=trt.Logger.VERBOSE,
  File "/opt/conda/lib/python3.8/site-packages/torch2trt-0.2.0-py3.8-linux-x86_64.egg/torch2trt/torch2trt.py", line 557, in torch2trt
    ctx.mark_outputs(outputs, output_names)
  File "/opt/conda/lib/python3.8/site-packages/torch2trt-0.2.0-py3.8-linux-x86_64.egg/torch2trt/torch2trt.py", line 418, in mark_outputs
    trt_tensor = torch_output._trt
AttributeError: 'Tensor' object has no attribute '_trt'

What I'm doing wrong?

**Comment by kamilrzechowski** [comment]
Solved. from .matmul import * needs to be added in the __init__.py

**Comment by jaybdub** [comment]
Hi @kamilrzechowski ,

Thanks for reaching out!

Glad to hear you were able to resolve this yourself.  I'll try to add this converter upstream soon.

FYI, for testing new converters, you can also add the converters inline by adding the ``@tensorrt_converter`` code before calling ``torch2trt(...)``.  The latest call to ``@tensorrt_converter`` before calling ``torch2trt(...)`` will override previous definitions.

This is sometimes helpful when debugging because you don't need to modify ``torch2trt`` package.

Best,
John

**Comment by tuqingyun** [comment]
@kamilrzechowski
Do you have solved this problem?
