### ISSUE TITLE
How to create TensorRT engine plan file for a different architecture ? 

### ISSUE THREAD

**Issue by newforrestgump001** [NVIDIA-AI-IOT/torch2trt#658]
For example, I want to create a plan file for 1070ti (on another pc)  with the 2080ti, Is it possible? Thanks!

**Comment by jaybdub** [comment]
Hi @newforrestgump001,

Thanks for reaching out!

Unfortunately, because TensorRT queries available tactics based on the architecture, and runs various device-specific profiling during the optimization phase, this isn't currently possible.

Hope this helps, let me know if you have any other questions.

Best,
John

**Comment by newforrestgump001** [comment]
@jaybdub  Thank you a lot for your reply.
